declare module '@next/eslint-plugin-next'
declare module 'eslint-plugin-import'
declare module 'eslint-plugin-jsx-a11y'
declare module 'eslint-plugin-sort-destructure-keys'
declare module 'eslint-plugin-sort-keys-fix'
declare module 'eslint-plugin-typescript-sort-keys'
